#!/usr/bin/env bash
# Displays Best School 10 times.

i=0

while [[ $i -le 9 ]]; do
    if [[ "$i" -eq 8 ]]; then
        printf %b%s 'Best School\nHi\n'
    else
        echo "Best School"
    fi
    ((i++))
done
