#!/usr/bin/env bash
# Displays bad luck for the 4th loop iteration, good luck for the 8th
# loop iteration and Best School for the other iterations of the 10

i=0

while [[ $i -le 9 ]]; do
    if [[ "$i" -eq 3 ]]; then
        echo "bad luck"
    elif [[ "$i" -eq 7 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
