#!/usr/bin/env bash
# Displays 4 and then bad luck from China for the 4th loop iteration, bad 
# luck from Japan for the 9th loop iteration, displays 17 and then bad
# luck from Italy for the 17th loop iteration and the rest of numbers
# in range 1 - 20

i=1

while [[ $i -le 20 ]]; do
    case "$i" in
        4)   printf "%d\nbad luck from China\n" $i
             ;;
        9)   printf "%d\nbad luck from Japan\n" $i
             ;;
        17)   printf "%d\nbad luck from Italy\n" $i
              ;;
        *)   printf "%d\n" $i
             ;;
    esac
    ((i++))
done
