#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:display hours from 0
# to 12 and display minutes from 1 to 59.

i=0

while [[ $i -le 11 ]]; do
    printf "Hour: %d\n" $i
    min=1
    while [[ $min -le 59 ]]; do
        printf "%d\n" $min
        ((min++))
    done
    ((i++))
done
