#!/usr/bin/env bash
# Displays the content of the current directory(excluding hidden files)
# in a list format where only the part of the name after the first dash(-)
# is displayed i.e filename [8-for_ls = for_ls]

LIST="$(ls)"
for i in $LIST; do
    echo "$i" | cut -d- -f2
done
