#!/usr/bin/env bash
# Checks if the file 'school' exists, if the file is empty and the type
# of file it is
check_file="school"
if [[ -e "$check_file" ]]
then
    echo "school file exists"
    if [[ ! -s "$check_file" ]]
    then
        echo "school is empty"
    else
        echo "school is not empty"
    fi
    if [[ -f "$check_file" ]]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
