#!/usr/bin/env bash
# Checks if the file 'school' exists, if the file is empty and the type
# of file it is
check_file="school"
if [[ -e "$check_file" ]]
then
    echo "$check_file file exists"
    if [[ ! -s "$check_file" ]]
    then
        echo "$check_file is empty"
    else
        echo "$check_file is not empty"
    fi
    if [[ -f "$check_file" ]]
    then
        echo "$check_file is a regular file"
    fi
else
    echo "$check_file file does not exist"
fi
